---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: create directory and file
      file:
        path: /var/www/html/mydir/myfile.txt
        state: touch
        mode: '0644'
        owner: apache
        group: apache

    - name: change timezone
      timezone:
        name: America/New_York

    - name: run shell script
      shell: /path/to/my/script.sh
      args:
        chdir: /path/to/my/script/dir/
# ------------------------------------------------------------------
- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

    - name: create directory and file
      file:
        path: /var/www/html/mydir/myfile.txt
        state: touch
        mode: '0644'
        owner: apache
        group: apache

    - name: change timezone
      timezone:
        name: America/New_York

    - name: run shell script
      shell: /path/to/my/script.sh
      args:
        chdir: /path/to/my/script/dir/
...
