# ---
#- hosts: all
#- import_playbook: /ansible-conf-mangt-P11/static-assignments/common-del.yml

#- hosts: uat-webservers
#- import_playbook: ../static-assignments/uat-webservers.yml

#- hosts: webservers
#- name: Webserver assignment
#  import_playbook: ../static-assignments/webservers.yml


#- hosts: all
#- name: Include dynamic variables 
#  tasks:
#  import_playbook: ../static-assignments/common.yml 
#  include: ../dynamic-assignments/env-vars.yml
#  tags:
#    - always

#---
#- name: import common file
#  import_playbook: ../static-assignments/common.yml
#  tags:
#    - always

---
- hosts: all

- name: Include dynamic variables 
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: import webservers file
  import_playbook: ../static-assignments/webservers.yml


- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required

- name: import database file
  import_playbook: ../static-assignments/database.yml